modLoader = "javafml"
loaderVersion = "${forge_version}"
issueTrackerURL = "${issues}" #optional
license = "${license}"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
updateJSONURL= "${update}" #optional
displayURL = "${homepage}" #optional
authors = "${authors}" #optional
description = '''
${description}
'''
#logoFile = ""

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "${forge_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "architectury"
mandatory = true
versionRange = "${architectury_version}"
ordering = "AFTER"
side = "BOTH"
